<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE TOUCHGRAPH_LB [

<!ELEMENT TOUCHGRAPH_LB (NODESET, EDGESET, PARAMETERS)>
<!ELEMENT NODESET (NODE+)>
<!ELEMENT EDGESET (EDGE*)>
<!ELEMENT PARAMETERS (PARAM*)>

<!ELEMENT NODE (NODE_LOCATION?, NODE_LABEL?, NODE_URL?, NODE_HINT?)>

<!ELEMENT NODE_LABEL EMPTY>
<!ELEMENT NODE_URL EMPTY>
<!ELEMENT NODE_HINT EMPTY>

<!ATTLIST TOUCHGRAPH_LB
version CDATA #REQUIRED >

<!ATTLIST NODE
nodeID CDATA #REQUIRED >

<!ATTLIST NODE_LOCATION
visible CDATA #IMPLIED
x CDATA #IMPLIED
y CDATA #IMPLIED >

<!ATTLIST NODE_LABEL
label CDATA #REQUIRED
shape CDATA #IMPLIED
backColor CDATA #IMPLIED
textColor CDATA #IMPLIED
fontSize CDATA #IMPLIED >

<!ATTLIST NODE_URL
url CDATA #REQUIRED
urlIsLocal CDATA #IMPLIED
urlIsXML CDATA #IMPLIED >

<!ATTLIST NODE_HINT
hint CDATA #REQUIRED
height CDATA #IMPLIED
width CDATA #IMPLIED
isHTML CDATA #IMPLIED >

<!ELEMENT EDGE EMPTY>

<!ATTLIST EDGE
fromID CDATA #REQUIRED
toID CDATA #REQUIRED
length CDATA #IMPLIED
color CDATA #IMPLIED
type CDATA #IMPLIED
visible CDATA #IMPLIED >

<!ELEMENT PARAM EMPTY>

<!ATTLIST PARAM
name CDATA #REQUIRED
value CDATA #REQUIRED >
]>
<TOUCHGRAPH_LB version="1.20">
<NODESET>
  <NODE nodeID="border">
  <NODE_LOCATION visible="true" x="447" y="-31" />
  <NODE_LABEL label="border" shape="1" backColor="660000" textColor="ffff00" fontSize="20" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=border" />
  <NODE_HINT hint="cisco WS-C6509<br>border (130.113.69.4)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="JHESW">
  <NODE_LOCATION visible="true" x="508" y="26" />
  <NODE_LABEL label="JHESW" shape="2" backColor="660000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=JHESW" />
  <NODE_HINT hint="cisco WS-C6509<br>JHESW (130.113.69.5)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="kazoo">
  <NODE_LOCATION visible="true" x="432" y="106" />
  <NODE_LABEL label="kazoo" shape="2" backColor="660000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=kazoo" />
  <NODE_HINT hint="cisco WS-C3550-12T<br>kazoo (172.26.10.227)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="GHSW">
  <NODE_LOCATION visible="true" x="374" y="12" />
  <NODE_LABEL label="GHSW" shape="2" backColor="660000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=GHSW" />
  <NODE_HINT hint="cisco WS-C6509<br>GHSW (130.113.69.6)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="moulton-rt">
  <NODE_LOCATION visible="true" x="407" y="-145" />
  <NODE_LABEL label="moulton-rt" shape="2" backColor="660000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=moulton-rt" />
  <NODE_HINT hint="cisco WS-C4506<br>moulton-rt (130.113.69.37)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="mckay-rt">
  <NODE_LOCATION visible="true" x="508" y="-134" />
  <NODE_LABEL label="mckay-rt" shape="2" backColor="660000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=mckay-rt" />
  <NODE_HINT hint="cisco WS-C4506<br>mckay-rt (130.113.69.36)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="DBACSW1-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="DBACSW1-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=DBACSW1-A" />
  <NODE_HINT hint="cisco WS-C4506<br>DBACSW1-A (130.113.25.5)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="GSSW224-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="GSSW224-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=GSSW224-A" />
  <NODE_HINT hint="cisco WS-C4506<br>GSSW224-A (130.113.142.5)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="CUCSW1-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="CUCSW1-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=CUCSW1-A" />
  <NODE_HINT hint="cisco WS-C2924C-XL<br>CUCSW1-A (172.26.2.125)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="JHESWBB">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="JHESWBB" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=JHESWBB" />
  <NODE_HINT hint="WS-C4006<br>JHESWBB (172.26.2.177)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="Comp_Rm_2D11_4000_RSM">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="Comp_Rm_2D11_4000_RSM" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=Comp_Rm_2D11_4000_RSM" />
  <NODE_HINT hint="WS-C4006<br>Comp_Rm_2D11_4000_RSM (130.113.45.105)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="LSBSWBB">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="LSBSWBB" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=LSBSWBB" />
  <NODE_HINT hint="WS-C4006<br>LSBSWBB (172.26.2.58)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="TLSWB121-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="TLSWB121-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=TLSWB121-A" />
  <NODE_HINT hint="cisco WS-C2950G-24-EI<br>TLSWB121-A (172.26.2.139)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="ABBHostsSW">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="ABBHostsSW" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=ABBHostsSW" />
  <NODE_HINT hint="WS-C4006<br>ABBHostsSW (172.26.10.2)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="MGDSW-BB">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="MGDSW-BB" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=MGDSW-BB" />
  <NODE_HINT hint="WS-C4006<br>MGDSW-BB (172.26.2.191)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="ABBSWBB">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="ABBSWBB" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=ABBSWBB" />
  <NODE_HINT hint="cisco WS-C4006<br>ABBSWBB (130.113.54.5)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="IWCSWB201A-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="IWCSWB201A-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=IWCSWB201A-A" />
  <NODE_HINT hint="cisco WS-C4506<br>IWCSWB201A-A (172.26.2.241)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="20SWUB124-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="20SWUB124-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=20SWUB124-A" />
  <NODE_HINT hint="WS-C4006<br>20SWUB124-A (172.26.2.124)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="KTHSWB111A-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="KTHSWB111A-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=KTHSWB111A-A" />
  <NODE_HINT hint="WS-C4006<br>KTHSWB111A-A (172.26.2.81)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="TSHSWB134-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="TSHSWB134-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=TSHSWB134-A" />
  <NODE_HINT hint="cisco WS-C4506<br>TSHSWB134-A (172.26.2.240)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="TSHSW207A-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="TSHSW207A-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=TSHSW207A-A" />
  <NODE_HINT hint="WS-C4006<br>TSHSW207A-A (172.26.2.82)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="GH-CNHSW-BB">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="GH-CNHSW-BB" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=GH-CNHSW-BB" />
  <NODE_HINT hint="WS-C4006<br>GH-CNHSW-BB (172.26.2.219)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="hhsw107-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="hhsw107-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=hhsw107-A" />
  <NODE_HINT hint="WS-C4006<br>hhsw107-A (130.113.105.5)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="MLSW-BB">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="MLSW-BB" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=MLSW-BB" />
  <NODE_HINT hint="WS-C4006<br>MLSW-BB (172.26.2.138)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="52SW1N-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="52SW1N-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=52SW1N-A" />
  <NODE_HINT hint="cisco WS-C4506<br>52SW1N-A (130.113.144.3)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="T13SW121-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="T13SW121-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=T13SW121-A" />
  <NODE_HINT hint="cisco WS-C4506<br>T13SW121-A (172.26.2.7)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="ITBSWBB">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="ITBSWBB" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=ITBSWBB" />
  <NODE_HINT hint="WS-C4006<br>ITBSWBB (172.26.2.18)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="UHSWB134-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="UHSWB134-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=UHSWB134-A" />
  <NODE_HINT hint="cisco WS-C2924M-XL<br>UHSWB134-A (172.26.2.65)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="Cage-rt1">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="Cage-rt1" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=Cage-rt1" />
  <NODE_HINT hint="Cisco WS-C3550-12T<br>Cage-rt1 (172.26.20.161)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="CSWB101A-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="CSWB101A-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=CSWB101A-A" />
  <NODE_HINT hint="cisco WS-C2924M-XL<br>CSWB101A-A (172.26.2.75)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="PBSWBB">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="PBSWBB" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=PBSWBB" />
  <NODE_HINT hint="WS-C4006<br>PBSWBB (172.26.2.235)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="IAHSSWBB">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="IAHSSWBB" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=IAHSSWBB" />
  <NODE_HINT hint="WS-C6006<br>IAHSSWBB (172.26.2.36)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="BSBSWSBS-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="BSBSWSBS-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=BSBSWSBS-A" />
  <NODE_HINT hint="cisco WS-C4506<br>BSBSWSBS-A (130.113.168.1)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="NRBSW1-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="NRBSW1-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=NRBSW1-A" />
  <NODE_HINT hint="cisco WS-C2924M-XL<br>NRBSW1-A (172.26.2.143)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="CCASW1">
  <NODE_LOCATION visible="true" x="447" y="-200" />
  <NODE_LABEL label="CCASW1" shape="2" backColor="660000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=CCASW1" />
  <NODE_HINT hint="cisco WS-C2950C-24<br>CCASW1 (172.26.2.49)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="KTHSWB108A-B">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="KTHSWB108A-B" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=KTHSWB108A-B" />
  <NODE_HINT hint="cisco WS-C2950G-48-EI<br>KTHSWB108A-B (172.26.2.243)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="CRLSWBB">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="CRLSWBB" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=CRLSWBB" />
  <NODE_HINT hint="cisco WS-C3508G-XL<br>CRLSWBB (172.26.3.47)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="KTHSWB108A-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="KTHSWB108A-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=KTHSWB108A-A" />
  <NODE_HINT hint="cisco WS-C3508G-XL<br>KTHSWB108A-A (172.26.2.242)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="CRLSWB110-E">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="CRLSWB110-E" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=CRLSWB110-E" />
  <NODE_HINT hint="cisco WS-C3548-XL<br>CRLSWB110-E (172.26.3.51)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="TLSWB121-C">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="TLSWB121-C" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=TLSWB121-C" />
  <NODE_HINT hint="cisco WS-C2950G-48-EI<br>TLSWB121-C (172.26.2.141)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="hhsw107-B">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="hhsw107-B" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=hhsw107-B" />
  <NODE_HINT hint="WS-C4006<br>hhsw107-B (172.26.2.227)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="BSBSWSBS-B">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="BSBSWSBS-B" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=BSBSWSBS-B" />
  <NODE_HINT hint="cisco WS-C4506<br>BSBSWSBS-B (130.113.168.2)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="GHHostsSW">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="GHHostsSW" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=GHHostsSW" />
  <NODE_HINT hint="cisco WS-C4506<br>GHHostsSW (172.26.10.1)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="52SW1N-B">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="52SW1N-B" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=52SW1N-B" />
  <NODE_HINT hint="cisco WS-C4506<br>52SW1N-B (130.113.144.4)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="27SWB112-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="27SWB112-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=27SWB112-A" />
  <NODE_HINT hint="cisco WS-C3750-48TS<br>27SWB112-A (130.113.28.5)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="07SWGAR-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="07SWGAR-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=07SWGAR-A" />
  <NODE_HINT hint="cisco WS-C2950G-48-EI<br>07SWGAR-A (172.26.4.30)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="54SW104-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="54SW104-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=54SW104-A" />
  <NODE_HINT hint="cisco WS-C4506<br>54SW104-A (130.113.201.5)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="05SWB111B-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="05SWB111B-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=05SWB111B-A" />
  <NODE_HINT hint="cisco WS-C3750-24TS<br>05SWB111B-A (130.113.17.5)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="36SWB109A-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="36SWB109A-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=36SWB109A-A" />
  <NODE_HINT hint="cisco WS-C3750G-12S<br>36SWB109A-A (130.113.44.5)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="26SWB123-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="26SWB123-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=26SWB123-A" />
  <NODE_HINT hint="cisco WS-C3750G-12S<br>26SWB123-A (130.113.14.5)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="45SWB126-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="45SWB126-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=45SWB126-A" />
  <NODE_HINT hint="cisco WS-C3750G-12S<br>45SWB126-A (130.113.73.5)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="40SWB103-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="40SWB103-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=40SWB103-A" />
  <NODE_HINT hint="cisco WS-C3750G-12S<br>40SWB103-A (130.113.82.5)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="50SWB117-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="50SWB117-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=50SWB117-A" />
  <NODE_HINT hint="WS-C4006<br>50SWB117-A (130.113.110.5)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="35SWB105-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="35SWB105-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=35SWB105-A" />
  <NODE_HINT hint="cisco WS-C3750-48TS<br>35SWB105-A (130.113.89.5)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="18SWB105-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="18SWB105-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=18SWB105-A" />
  <NODE_HINT hint="cisco WS-C3750G-12S<br>18SWB105-A (172.26.20.128)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="06SWB106-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="06SWB106-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=06SWB106-A" />
  <NODE_HINT hint="cisco WS-C3750-24TS<br>06SWB106-A (130.113.18.5)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="19SWB102-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="19SWB102-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=19SWB102-A" />
  <NODE_HINT hint="cisco WS-C3750G-12S<br>19SWB102-A (130.113.36.5)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="DBACSW2-B">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="DBACSW2-B" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=DBACSW2-B" />
  <NODE_HINT hint="cisco WS-C4506<br>DBACSW2-B (172.26.3.36)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="DBACSW2-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="DBACSW2-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=DBACSW2-A" />
  <NODE_HINT hint="cisco WS-C4506<br>DBACSW2-A (172.26.3.35)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="GSSW-TASWB107-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="GSSW-TASWB107-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=GSSW-TASWB107-A" />
  <NODE_HINT hint="cisco WS-C2950G-48-EI<br>GSSW-TASWB107-A (172.26.2.150)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="GSSW318-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="GSSW318-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=GSSW318-A" />
  <NODE_HINT hint="cisco WS-C3548-XL<br>GSSW318-A (172.26.2.156)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="GSSW110-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="GSSW110-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=GSSW110-A" />
  <NODE_HINT hint="cisco WS-C3548-XL<br>GSSW110-A (172.26.2.152)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="CUCSW1-B">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="CUCSW1-B" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=CUCSW1-B" />
  <NODE_HINT hint="cisco WS-C2950G-48-EI<br>CUCSW1-B (172.26.2.126)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="CUCSW1-C">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="CUCSW1-C" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=CUCSW1-C" />
  <NODE_HINT hint="cisco WS-C2950G-48-EI<br>CUCSW1-C (172.26.2.127)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="JHESW234D-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="JHESW234D-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=JHESW234D-A" />
  <NODE_HINT hint="WS-C4006<br>JHESW234D-A (172.26.2.80)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="JHEWL1-B">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="JHEWL1-B" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=JHEWL1-B" />
  <NODE_HINT hint="cisco AIR-AP1231G-A-K9    <br>JHEWL1-B (172.26.11.195)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="JHESW-ANNEX-D">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="JHESW-ANNEX-D" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=JHESW-ANNEX-D" />
  <NODE_HINT hint="cisco WS-C3548-XL<br>JHESW-ANNEX-D (172.26.2.162)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="JHEWL121-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="JHEWL121-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=JHEWL121-A" />
  <NODE_HINT hint="cisco AIR-AP1231G-A-K9    <br>JHEWL121-A (172.26.11.59)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="JHESW2-C">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="JHESW2-C" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=JHESW2-C" />
  <NODE_HINT hint="cisco WS-C2950G-48-EI<br>JHESW2-C (172.26.2.170)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="JHESW3-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="JHESW3-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=JHESW3-A" />
  <NODE_HINT hint="cisco WS-C3548-XL<br>JHESW3-A (172.26.2.173)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="JHESW2-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="JHESW2-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=JHESW2-A" />
  <NODE_HINT hint="cisco WS-C2950G-48-EI<br>JHESW2-A (172.26.2.168)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="JHESW3-C">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="JHESW3-C" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=JHESW3-C" />
  <NODE_HINT hint="cisco WS-C2950G-48-EI<br>JHESW3-C (172.26.2.175)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="JHESW-ANNEX-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="JHESW-ANNEX-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=JHESW-ANNEX-A" />
  <NODE_HINT hint="cisco WS-C3548-XL<br>JHESW-ANNEX-A (172.26.2.160)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="DCSW-BB">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="DCSW-BB" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=DCSW-BB" />
  <NODE_HINT hint="cisco WS-C2924M-XL<br>DCSW-BB (172.26.2.53)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="LSBSW222-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="LSBSW222-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=LSBSW222-A" />
  <NODE_HINT hint="cisco WS-C2950G-48-EI<br>LSBSW222-A (172.26.2.59)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="WHSWB201-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="WHSWB201-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=WHSWB201-A" />
  <NODE_HINT hint="cisco WS-C2924C-XL<br>WHSWB201-A (172.26.2.55)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="LSBSW431-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="LSBSW431-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=LSBSW431-A" />
  <NODE_HINT hint="cisco WS-C2950G-48-EI<br>LSBSW431-A (172.26.2.61)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="LSBSW116-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="LSBSW116-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=LSBSW116-A" />
  <NODE_HINT hint="cisco WS-C2950G-48-EI<br>LSBSW116-A (172.26.2.63)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="LSBSW333-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="LSBSW333-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=LSBSW333-A" />
  <NODE_HINT hint="cisco WS-C2950G-48-EI<br>LSBSW333-A (172.26.2.60)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="LSBSW534-A">
  <NODE_LOCATION visible="" x="500" y="0" />
  <NODE_LABEL label="LSBSW534-A" shape="2" backColor="880000" textColor="ffff00" fontSize="15" />
  <NODE_URL url="http://netmap.mcmaster.ca/node?sysname=LSBSW534-A" />
  <NODE_HINT hint="cisco WS-C2950G-48-EI<br>LSBSW534-A (172.26.2.62)" isHTML='true' width="250" height="100" />
  </NODE>
  <NODE nodeID="TLSWB121-D">
  <NODE_LOCATION visible="" x="500" y="0" />